### PR TITLE
Use regexp to extract ISBN candidate in normalizeISBN($raw)

### PR DESCRIPTION
**Pull request by julianladisch**
As discussed in https://github.com/vufind-org/vufindcode/pull/3

### CODE REVIEW

**Comment by julianladisch** [comment]
Feel free to add more test cases that should be accepted/extracted to the unit tests.

**Comment by demiankatz** [comment]
Thanks, @julianladisch, this looks good. One possibility before I merge: how would you feel about ignoring/filtering non-word characters (`\W`) and underscores rather than only whitespace, periods and dashes? That might cover other unanticipated delimiters while still protecting against common problematic edge cases like the UUID one.

**Comment by julianladisch** [comment]
Yes, \W|_ should make it reasonably backwards compatible.

**Comment by demiankatz** [comment]
@julianladisch, I tried `\W|_` as I proposed and it ended up breaking many of your test cases in weird ways, suggesting that broader matching is definitely not necessarily better. I've rolled things back to your original proposal, only with underscore added, and I set up the lookahead as a `[...]` character class to make it easier to add additional characters in future if the need arises. We could also consider a negative character class like `[^a-zA-Z:(]` to capture more broadly while avoiding obvious problem cases, but I think for now I'll keep things as you set them up. Thanks again for taking the time to help improve the library. I'll wait until I hear from you before merging in case you have any final thoughts, but as far as I'm concerned, I think this is ready to go!

**Comment by julianladisch** [comment]
Sounds reasonable.
Please add '_' to the normalizeISBN($raw) documentation, and 'ISBN-10 underscore' and 'ISBN-13 underscore' example to validISBN10() of ISBNTest.php.

**Comment by demiankatz** [comment]
@julianladisch, thanks again -- I've made your suggested adjustments and will merge now.

**Pull request merged**
